version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: wiccapedia-postgres
    environment:
      POSTGRES_DB: wiccapedia
      POSTGRES_USER: wiccapedia_user
      POSTGRES_PASSWORD: wiccapedia_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - wiccapedia-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wiccapedia_user -d wiccapedia"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: wiccapedia-minio
    environment:
      MINIO_ROOT_USER: wiccapedia_admin
      MINIO_ROOT_PASSWORD: wiccapedia_admin_password
      MINIO_DEFAULT_BUCKETS: gem-images
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - wiccapedia-network
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO client to create buckets and setup policies
  minio-setup:
    image: minio/mc:latest
    container_name: wiccapedia-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: wiccapedia_admin
      MINIO_SECRET_KEY: wiccapedia_admin_password
    networks:
      - wiccapedia-network
    entrypoint: >
      /bin/sh -c "
      echo 'Setting up MinIO...';
      /usr/bin/mc alias set myminio http://minio:9000 wiccapedia_admin wiccapedia_admin_password;
      /usr/bin/mc mb myminio/gem-images --ignore-existing;
      /usr/bin/mc policy set public myminio/gem-images;
      echo 'MinIO setup completed';
      "

  redis:
    image: redis:7-alpine
    container_name: wiccapedia-redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "wiccapedia_redis_password"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wiccapedia-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  wiccapedia-network:
    driver: bridge
