// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WiccapediaApi.Data;

#nullable disable

namespace WiccapediaApi.Migrations
{
    [DbContext(typeof(WiccapediaDbContext))]
    [Migration("20260306030619_NotebookDomainRefactor")]
    partial class NotebookDomainRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WiccapediaApp.Models.Notebooks.Notebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverLottieData")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notebooks");
                });

            modelBuilder.Entity("WiccapediaApp.Models.Notebooks.NotebookPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NextPageId")
                        .HasColumnType("integer");

                    b.Property<int>("NotebookId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousPageId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NextPageId");

                    b.HasIndex("PreviousPageId");

                    b.HasIndex("NotebookId", "IsCover")
                        .IsUnique()
                        .HasFilter("\"IsCover\" = true");

                    b.ToTable("NotebookPages");
                });

            modelBuilder.Entity("WiccapediaApp.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WiccapediaApp.Models.Notebooks.Notebook", b =>
                {
                    b.HasOne("WiccapediaApp.Models.Users.User", "User")
                        .WithMany("Notebooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WiccapediaApp.Models.Notebooks.NotebookPage", b =>
                {
                    b.HasOne("WiccapediaApp.Models.Notebooks.NotebookPage", "NextPage")
                        .WithMany()
                        .HasForeignKey("NextPageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WiccapediaApp.Models.Notebooks.Notebook", "Notebook")
                        .WithMany("Pages")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WiccapediaApp.Models.Notebooks.NotebookPage", "PreviousPage")
                        .WithMany()
                        .HasForeignKey("PreviousPageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NextPage");

                    b.Navigation("Notebook");

                    b.Navigation("PreviousPage");
                });

            modelBuilder.Entity("WiccapediaApp.Models.Notebooks.Notebook", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("WiccapediaApp.Models.Users.User", b =>
                {
                    b.Navigation("Notebooks");
                });
#pragma warning restore 612, 618
        }
    }
}
